function readMeGenerator(response) {
    return `
<h1 align="center">${response.projectTitle} </h1>

## ✨Overview (description)✨
<h3 align="center">${response.description}</h3>

## License
This application is  covered by the ${response.license}

## 👀Preview and Demo
 
Link to Demo: ${response.demoLink}


## 📋Table of Contents
-[License](#license) <br />
-[Description](#description) <br />
-[Installation](#💢📃Installation) <br />
-[Usage](#🧰Usage) <br />
-[Contribute](#🏠Contributors) <br />
-[Tests](#🧪Tests) <br />
-[Questions](#🤔Questions) <br />


## 💢📃Installation
To clone and use this application, you'll need Git and Node.js (npm equipped) installed on your computer


## 🧰Usage
${response.usage}

## 🏠Contributors
${response.contribute}

## 🧪Tests
Are tests included in this application?: ${response.tests}


## 🤔Questions
Find me on Github: ${response.questions} <br />
<br />
If you have any questions or concerns please contact me through email: ${response.email} or GitHub

## 🪙 Support
This is FREE, OPEN-SOURCE software. <br />
If you'd like to support the development of future projects or "say thanks," you can donate BTC at: ${response.btc}.


<h3 align="center">This ReadMe was generated by KHIAOTIC and coded with 🌈💖</h3>
`;
}

module.exports = readMeGenerator;

